spring:
  shardingsphere:
    # 属性配置
    props:
      # 是否开启 SQL 显示，默认值: false
      sql:
        show: true
    # 数据源配置，可配置多个
    datasource:
      # 本案例中配置了两个数据源，分别对应刚才创建的两个 MySQL 容器
      names: ds0,ds1
      ds0:
        type: com.zaxxer.hikari.HikariDataSource
        driver-class-name: com.mysql.jdbc.Driver
        jdbc-url: jdbc:mysql://192.168.0.130:3310/mytest_0?useUnicode=true&characterEncoding=utf-8&serverTimezone=Hongkong&useSSL=false
        username: root
        password: '123456'
        hikari:
          minimum-idle: 5
          idle-timeout: 600000
          maximum-pool-size: 10
          auto-commit: true
          pool-name: MyHikariCP
          max-lifetime: 1800000
          connection-timeout: 30000
          connection-test-query: SELECT 1
      ds1:
        type: com.zaxxer.hikari.HikariDataSource
        driver-class-name: com.mysql.jdbc.Driver
        jdbc-url: jdbc:mysql://192.168.0.130:3311/mytest_1?useUnicode=true&characterEncoding=utf-8&serverTimezone=Hongkong&useSSL=false
        username: root
        password: '123456'
        hikari:
          minimum-idle: 5
          idle-timeout: 600000
          maximum-pool-size: 10
          auto-commit: true
          pool-name: MyHikariCP
          max-lifetime: 1800000
          connection-timeout: 30000
          connection-test-query: SELECT 1
    # 分片规则配置
    sharding:
      # 绑定表规则列表
      binding-tables: p_order
      # 默认数据库分片策略，同分库策略
      default-database-strategy:
        inline:
          # 分片算法行表达式，需符合 groovy 语法
          # 此处根据 serial_no 分片
          # 如果 serial_no 为奇数则落入奇数库即 ds1 匹配的数据源
          # 如果 serial_no 为偶数则落入偶数库即 ds0 匹配的数据源
          algorithm-expression: ds$->{serial_no % 2}
          # 分片列名称
          sharding-column: serial_no
      # 数据分片规则配置，可配置多个
      tables:
        # 逻辑表名称
        p_order:
          # 由数据源名 + 表名组成，以小数点分隔
          actual-data-nodes: ds$->{0..1}.p_order_$->{0..15}
          # 分表策略，同分库策略
          table-strategy:
            inline:
              # 此处根据 pay_method_id 分片
              # 根据 pay_method_id % 16 的结果，落入对应的表
              algorithm-expression: p_order_$->{pay_method_id % 16}
              # 分片列名称
              sharding-column: pay_method_id

mybatis:
  type-aliases-package: com.miwang.shardingsphere.entity
  mapper-locations: classpath:mapper/*.xml
