server:
  port: 8081
  servlet:
    context-path: /
  address: 0.0.0.0
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/foreign_exchange_a?useUnicode=true&characterEncoding=utf8&useSSL=false
    username: root
    password: 123456

mybatis:
  type-aliases-package: org.dromara.hmily.demo.common.account.entity
  config-location: classpath:mybatis/mybatis-config.xml

logging:
  level:
    root: error
    org.springframework.web: info
    org.dromara.hmily.demo.bonuspoint: debug
    org.dromara.hmily.demo.lottery: debug
    org.dromara.hmily.demo: debug
  path: "./logs"